services:
  - type: web
    name: moeda-estudantil-api
    env: java
    buildCommand: mvn clean install -DskipTests
    startCommand: java -jar target/estudantil-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod